# This workflow will build and push a web application to an Azure Static Web App when you change your code.
#
# This workflow assumes you have already created the target Azure Static Web App.
# For instructions see https://docs.microsoft.com/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_STATIC_WEB_APPS_API_TOKEN with the value of your Static Web Apps deployment token.
#    For instructions on obtaining the deployment token see: https://docs.microsoft.com/azure/static-web-apps/deployment-token-management
#
# 3. Change the values for the APP_LOCATION, API_LOCATION and APP_ARTIFACT_LOCATION, AZURE_STATIC_WEB_APPS_API_TOKEN environment variables (below).
#    For instructions on setting up the appropriate configuration values go to https://docs.microsoft.com/azure/static-web-apps/front-end-frameworks
name: github_actions_test build

on:
  push:
    branches:
      - staging
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - staging

# Environment variables available to all jobs and steps in this workflow
env:
  APP_LOCATION: "/" # location of your client code
  API_LOCATION: "api" # location of your api source code - optional
  APP_ARTIFACT_LOCATION: "out" # location of client code build output
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing deployment token for your static web app
  
  # GITHUB_REF: PR merge branch refs/pull/:prNumber/merge
  # See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  PR_NUMBER: "`echo $GITHUB_REF | sed -e 's/[^0-9]//g'`"

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: echo PR_NUMBER
        run: |
          echo PR_NUMBER: ${{ env.PR_NUMBER }}
  
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Set env FRONTEND_ENDPOINT
        run: |
          if [[ $GITHUB_EVENT_NAME == 'push' ]]; then
            # $GITHUB_ENV
            # See: https://docs.github.com/ja/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
            echo "FRONTEND_ENDPOINT='https://ashy-pond-0cc79e810.1.azurestaticapps.net/'" >> "$GITHUB_ENV"
          else
            # pre-production environment(実稼働前環境)のURL: https://<SUBDOMAIN-PULL_REQUEST_ID>.<AZURE_REGION>.azurestaticapps.net
            # See: https://docs.microsoft.com/ja-jp/azure/static-web-apps/review-publish-pull-requests#review-changes
            echo "FRONTEND_ENDPOINT='https://ashy-pond-0cc79e810-${{ env.PR_NUMBER }}.centralus.1.azurestaticapps.net/'" >> "$GITHUB_ENV"
          fi

      - name: Echo env FRONTEND_ENDPOINT
        run: |
          echo FRONTEND_ENDPOINT: ${{ env.FRONTEND_ENDPOINT }}
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          PUBLIC_FRONTEND_ENDPOINT: ${{ env.FRONTEND_ENDPOINT }}
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing api token for app
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
          ###### End of Repository/Build Configurations ######

      - name: Echo env PUBLIC_FRONTEND_ENDPOINT
        run: |
          echo PUBLIC_FRONTEND_ENDPOINT: ${{ env.PUBLIC_FRONTEND_ENDPOINT }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing api token for app
          action: "close"
