# This is a basic workflow to help you get started with Actions

# Workflow syntax for GitHub Actions (GitHub Actionsのワークフロー構文)
# See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: github_actions_test unittest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - feat/*
      - fix/*
      - patch/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # GITHUB_REF: PR merge branch refs/pull/:prNumber/merge
  # See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  PR_NUMBER: "`echo $GITHUB_REF | sed -e 's/[^0-9]//g'`"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Set env FRONTEND_ENDPOINT
        run: |
          if [[ $GITHUB_EVENT_NAME == 'push' ]]; then
            # $GITHUB_ENV
            # See: https://docs.github.com/ja/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
            echo "FRONTEND_ENDPOINT='https://ashy-pond-0cc79e810.1.azurestaticapps.net/'" >> "$GITHUB_ENV"
          else
            # pre-production environment(実稼働前環境)のURL: https://<SUBDOMAIN-PULL_REQUEST_ID>.<AZURE_REGION>.azurestaticapps.net
            # See: https://docs.microsoft.com/ja-jp/azure/static-web-apps/review-publish-pull-requests#review-changes
            echo "FRONTEND_ENDPOINT='https://ashy-pond-0cc79e810-${{ env.PR_NUMBER }}.centralus.1.azurestaticapps.net/'" >> "$GITHUB_ENV"
          fi
          #echo FRONTEND_ENDPOINT: ${{ env.FRONTEND_ENDPOINT }} #この段階では env.FRONTEND_ENDPOINT は設定されてない
          
      - name: echo env FRONTEND_ENDPOINT
        run: |
          echo FRONTEND_ENDPOINT: ${{ env.FRONTEND_ENDPOINT }}
